name: Develop

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: ls
      run: ls
    - name: ls1
      run: ls src
    - name: ls2
      run: ls $GITHUB_WORKSPACE
    - name: Restore with dotnet
      run: dotnet restore src/BlazAdmin.ServerRender/BlazAdmin.ServerRender.csproj --configfile nuget.config
    - name: Build with dotnet
      run: dotnet build src/BlazAdmin.ServerRender/BlazAdmin.ServerRender.csproj --configuration Release
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
      with: 
        token: ${{secrets.github_token}}
    - name: pack nuget
      run: dotnet pack src/BlazAdmin.ServerRender/BlazAdmin.ServerRender.csproj /p:PackageVersion=0.0.2.${BUILD_NUMBER}-develop -c Release --no-build --no-restore
    - name: push nuget
      run: dotnet nuget push src/BlazAdmin.ServerRender/bin/Release/BlazAdmin.ServerRender.0.0.2.${BUILD_NUMBER}-develop.nupkg -s https://www.myget.org/F/wzxinchen-blazor/api/v2/package  -k 2564e20d-4cd4-482e-ba4b-daf05e2effa8
