name: .NET Core

on:
  push:
    branches: 
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build src/BlazAdmin.ServerRender/BlazAdmin.ServerRender.csproj --configuration Release
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
      with: 
        token: ${{secrets.github_token}}
    - name: pack nuget
      run: dotnet pack src/BlazAdmin.ServerRender/BlazAdmin.ServerRender.csproj /p:PackageVersion=0.0.1.${BUILD_NUMBER} -c Release --no-build --no-restore
    - name: push nuget
      run: dotnet nuget push src/BlazAdmin.ServerRender/bin/Release/BlazAdmin.ServerRender.0.0.1.${BUILD_NUMBER}.nupkg -s https://api.nuget.org/v3/index.json  -k oy2d44fv6wifoxdcwgkas7iwi37eahuexbsilepbewbnnu
